#!/usr/bin/env python3

import RPi.GPIO as GPIO
import curses
import time
import rospy
from time import sleep
from std_msgs.msg import String

pub=rospy.Publisher('talker',String,queue_size=20)
rospy.init_node('talker',anonymous=True)

en = 25
in1 = 23
in2 = 24
en1 = 17
in3 = 22
in4 = 27
temp1 = 1

GPIO.setmode(GPIO.BCM)
GPIO.setup(in1,GPIO.OUT)
GPIO.setup(in2,GPIO.OUT)
GPIO.setup(in3,GPIO.OUT)
GPIO.setup(in4,GPIO.OUT)
GPIO.setup(en,GPIO.OUT)

GPIO.setup(en1,GPIO.OUT)
GPIO.setup(in1,GPIO.LOW)
GPIO.setup(in2,GPIO.LOW)
GPIO.setup(in3,GPIO.LOW)
GPIO.setup(in4,GPIO.LOW)

p1 = GPIO.PWM(en,1000)
p2 = GPIO.PWM(en1,1000)

GPIO.output(in1,GPIO.LOW)
GPIO.output(in2,GPIO.LOW)
GPIO.output(in3,GPIO.LOW)
GPIO.output(in4,GPIO.LOW)

p1.start(25)
p2.start(25)
w='working'
rospy.loginfo(w)

screen = curses.initscr()
curses.noecho()
curses.cbreak()
screen.keypad(True)
GPIO.output(in2,GPIO.LOW)

def forward():
    GPIO.output(in1,GPIO.HIGH)
    GPIO.output(in2,GPIO.LOW)
    GPIO.output(in3,GPIO.HIGH)
    GPIO.output(in4,GPIO.LOW)
def backward():
    GPIO.output(in1,GPIO.LOW)
    GPIO.output(in2,GPIO.HIGH)
    GPIO.output(in3,GPIO.LOW)
    GPIO.output(in4,GPIO.HIGH)
def right():
    GPIO.output(in1,GPIO.HIGH)
    GPIO.output(in2,GPIO.LOW)
    GPIO.output(in3,GPIO.LOW)
    GPIO.output(in4,GPIO.LOW)
def left():
    GPIO.output(in1,GPIO.LOW)
    GPIO.output(in2,GPIO.LOW)
    GPIO.output(in3,GPIO.HIGH)
    GPIO.output(in4,GPIO.LOW)
def back_right():
    GPIO.output(in1,GPIO.LOW)
    GPIO.output(in2,GPIO.LOW)
    GPIO.output(in3,GPIO.LOW)
    GPIO.output(in4,GPIO.HIGH)
def back_left():
    GPIO.output(in1,GPIO.LOW)
    GPIO.output(in2,GPIO.HIGH)
    GPIO.output(in3,GPIO.LOW)
    GPIO.output(in4,GPIO.LOW)
def brake():
    GPIO.output(in1,GPIO.LOW)
    GPIO.output(in2,GPIO.LOW)
    GPIO.output(in3,GPIO.LOW)
    GPIO.output(in4,GPIO.LOW)
try:
    while True:
        char = screen.getch()
        f='MOVING FORWARD'
        b='MOVING BACKWARD'
        r='TURNING RIGHT'
        l='TURNING LEFT'
        br='TURNING BACK RIGHT'
        bl='TURNING BACK LEFT'
        
        if char == ord('A'):
            A='RECIEVED LETTER A'
            rospy.loginfo(A)
            pub.publish(A)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo(r)
            pub.publish(r)
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo(r)
            pub.publish(r)
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo(b)
            pub.publish(b)
            backward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo(bl)
            pub.publish(bl)
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            backward()
            sleep(1.5)
            brake()
            sleep(0.5)
        if char == ord('B'):
            B="RECIEVED LETTER B"
            rospy.loginfo(B)
            pub.publish(B)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo(r)
            pub.publish(r)
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo(r)
            pub.publish(r)
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo(r)
            pub.publish(r)
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(f)
            pub.publish(f)
            forward()
            sleep(2)
            brake()
            sleep(0.5)
            rospy.loginfo(b)
            pub.publish(b)
            backward()
            sleep(2)
            brake()
            sleep(0.5)
            rospy.loginfo(br)
            pub.publish(br)
            back_right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo(b)
            pub.publish(b)
            backward()
            sleep(2)
            brake()
            sleep(0.5)
            rospy.loginfo(br)
            pub.publish(br)
            back_right()
            sleep(2)
            brake()
            sleep(0.5)
            rospy.loginfo(b)
            pub.publish(b)
            backward()
            sleep(2)
            brake()
            sleep(0.5)
        if char == ord('!'):
            GPIO.cleanup()
            break
        if char == ord('C'):
            rospy.loginfo("RECIEVED LETTER C")
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('D'):
            rospy.loginfo("RECIEVED LETTER D")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('E'):
            rospy.loginfo("RECIEVED LETTER E")
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.6)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.6)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('F'):
            rospy.loginfo("RECIEVED LETTER F")
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
        if char == ord('G'):
            rospy.loginfo("Recieved letter G")
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
        if char == ord('H'):
            rospy.loginfo("RECIEVED LETTER H")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BAACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('I'):
            rospy.loginfo("RECIEVED LETTER I")
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.25)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('J'):
            rospy.loginfo("RECIEVED LETTER J")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.4)
            brake()
            sleep()
        if char == ord('K'):
            rospy.loginfo("RECIEVED LETTER K")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.707)
            brake()
            sleep(0.5)
        if char == ord('L'):
            rospy.loginfo("RECIEVED LETTER L")
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
        if char == ord('M'):
            rospy.loginfo("RECIEVED LETTER M")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('N'):
            rospy.loginfo("RECIEVED LETTER N")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.414)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('O'):
            rospy.loginfo("RECIEVED LETTER O")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()#90 degrees
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.60)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.60)
            brake()
            sleep(0.5)
        if char == ord('P'):
            rospy.loginfo("RECIEVED LETTER P")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
        if char == ord('Q'):
            rospy.loginfo("RECIEVED LETTER Q")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()#90 degrees
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.75)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK RIGHT")
            back_right()
            sleep(0.5)#45 degrees
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.25)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.5)
            brake()
            sleep(0.5)
        if char == ord('R'):
            rospy.loginfo("RECIEVED LETTER R")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)#90 degrees
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK RIGHT")
            back_right()
            sleep(0.5)#45 degrees
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.1)
            brake()
            sleep(0.5)
        if char == ord('S'):
            rospy.loginfo("RECIEVED LETTER S")
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('T'):
            rospy.loginfo("RECIEVED LETTER T")
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.35)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.35)
            brake()
            sleep(0.5)
        if char == ord('U'):
            rospy.loginfo("RECIEVED LETTER U")
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING LEFT")
            left()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
        if char == ord('V'):
            rospy.loginfo("RECIVED LETTER V")
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)#30 degrees
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.11)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1.11)
            brake()
            sleep(0.5)
        if char == ord('W'):
            rospy.loginfo("RECIEVED LETTER W")
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(0.5)#45
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.30)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.30)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
        if char == ord('X'):
            rospy.loginfo("RECIEVED LETTER X")
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(1)#45
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.414)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.414)
            brake()
            sleep(0.5)
        if char == ord('Y'):
            rospy.loginfo("RECIEVED LETTER Y")
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)#45
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.707)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(0.75)
            brake()
            sleep(0.5)
        if char == ord('Z'):
            rospy.loginfo("RECIEVED LETTER Z")
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(1)#90
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACK LEFT")
            back_left()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING BACKWARD")
            backward()
            sleep(1.414)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING RIGHT")
            right()
            sleep(0.5)
            brake()
            sleep(0.5)
            rospy.loginfo("MOVING FORWARD")
            forward()
            sleep(1)
            brake()
            sleep(0.5)
finally:
    curses.nocbreak();screen.keypad(0);curses.echo()
    curses.endwin()
    GPIO.cleanup()
    


